version: '3.8'

services:
  server:
    build: ./
    command: ./bin/bot
    ports:
      - 8010:8080
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - 8020:27017